# Generated by Django 4.0 on 2024-11-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='ShopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.TextField(max_length=500, verbose_name='商品説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('condition', models.CharField(choices=[('great', '新品に近い状態'), ('good', '状態が良い'), ('bad', '状態があまり良くない')], max_length=50, verbose_name='状態')),
                ('product_image', models.ImageField(upload_to='product_images', verbose_name='商品写真')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='出品日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('creditcard', 'クレジットカード'), ('realmoney', '現金'), ('electronic_money', '電子マネー')], max_length=50, verbose_name='支払方法')),
                ('order_day', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoppost', verbose_name='商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='購入者名')),
            ],
        ),
    ]
